AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VPCID:
    Type: 'AWS::EC2::VPC::Id'
  ESDOMAIN:
    Type: String
  HOSTZONE:
    Type: String
  TARGETIP:
    Type: String
  PRIORITY:
    Type: Number
  ACMARN:
    Type: String
  ALBDNSNAME:
    Type: String
  ALBHOSTEDZONEID:
    Type: String
  LOADBALANCERARN:
    Type: String
Resources:
  HTTPLISTENER:
     Type: AWS::ElasticLoadBalancingV2::Listener
     Properties:
       DefaultActions:
         - Type: 'fixed-response'
           FixedResponseConfig:
             StatusCode: 503
       LoadBalancerArn: !Ref LOADBALANCERARN
       Port: '443'
       Protocol: 'HTTPS'
       Certificates:
         - CertificateArn: !Ref ACMARN
  HTTPLISTENER80:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        DefaultActions:
          - Type: 'fixed-response'
            FixedResponseConfig:
              StatusCode: 503
        LoadBalancerArn: !Ref LOADBALANCERARN
        Port: '80'
        Protocol: 'HTTP'
  TARGETGROUP:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: !Ref ESDOMAIN
      VpcId: !Ref VPCID
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckPort: '443'
      HealthCheckProtocol: HTTPS
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: '200'
      Port: '443'
      Protocol: HTTPS
      TargetType: ip
      Targets:
        - Id: !Ref TARGETIP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 300
  LISTENERRULE:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TARGETGROUP
      Conditions:
        - Field: host-header
          Values:
            - !Sub ${ESDOMAIN}-es.${HOSTZONE}*
      ListenerArn: !Ref HTTPLISTENER
      Priority: !Ref PRIORITY
  ROUTE53RECORDSET:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HOSTZONE
      Comment: DNS name for my instance.
      RecordSets:
        - Name: !Sub ${ESDOMAIN}-es.${HOSTZONE}
          Type: A
          AliasTarget:
            DNSName: !Ref ALBDNSNAME
            HostedZoneId: !Ref ALBHOSTEDZONEID
