AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Nest Template Parent
Parameters:
  SUBNETPUBLIC1A:
    Type: 'AWS::EC2::Subnet::Id'
  SUBNETPUBLIC1C:
    Type: 'AWS::EC2::Subnet::Id'
  VPCID:
    Type: 'AWS::EC2::VPC::Id'
  ALBNAME:
    Type: String
    Default: proxy-xmdvpc-devel
  ESDOMAIN:
    Type: String
  HOSTZONE:
    Type: String
    Default: "nbi-prod.local."
  TARGETIP:
    Type: String
  PRIORITY:
    Type: Number
    Default: 10
  SUBNETPUBLIC1A:
    Type: 'AWS::EC2::Subnet::Id'
  SUBNETPUBLIC1C:
    Type: 'AWS::EC2::Subnet::Id'
  ACMARN:
    Type: String
  OFFICEIP:
    Type: String
    Default: "219.119.139.124/32"
Resources:
  CREATEALB:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./albproxy_parent.yml
      Parameters:
        VPCID: !Ref VPCID
        ALBNAME: !Ref ALBNAME
        ESDOMAIN: !Ref ESDOMAIN
        OFFICEIP: !Ref OFFICEIP
        ACMARN: !Ref ACMARN
        TARGETIP: !Ref TARGETIP
        SUBNETPUBLIC1A: !Ref SUBNETPUBLIC1A
        SUBNETPUBLIC1C: !Ref SUBNETPUBLIC1C
        HOSTZONE: !Ref HOSTZONE
  CHILD01:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./albproxy_child.yml
      Parameters:
        ESDOMAIN: test01
        TARGETIP: 10.0.0.101
        PRIORITY: 101
        VPCID: !Ref VPCID
        ACMARN: !Ref ACMARN
        HOSTZONE: !Ref HOSTZONE
        LOADBALANCERARN: !GetAtt
          - CREATEALB
          - Outputs.LOADBALANCERARN
        ALBHOSTEDZONEID: !GetAtt
          - CREATEALB
          - Outputs.ALBHOSTEDZONEID
        ALBDNSNAME: !GetAtt
          - CREATEALB
          - Outputs.ALBDNSNAME
  CHILD02:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./albproxy_child.yml
      Parameters:
        ESDOMAIN: test02
        TARGETIP: 10.0.0.102
        PRIORITY: 102
        VPCID: !Ref VPCID
        ACMARN: !Ref ACMARN
        HOSTZONE: !Ref HOSTZONE
        LOADBALANCERARN: !GetAtt
          - CREATEALB
          - Outputs.LOADBALANCERARN
        ALBHOSTEDZONEID: !GetAtt
          - CREATEALB
          - Outputs.ALBHOSTEDZONEID
        ALBDNSNAME: !GetAtt
          - CREATEALB
          - Outputs.ALBDNSNAME
